### ISSUE TITLE
Freddy's current behavior when a JSON dictionary has multiple keys of same name is not consistent with other systems. 

### ISSUE THREAD

**Issue by zorn** [bignerdranch/Freddy#106]
Currently if a JSON source, which contains a dictionary and that dictionary contains multiple uses of the same key, is parsed with Freddy the second value is returned. In comparison in my testing SwiftyJSON and Argo (which are both based on `NSJSONSerialization`) the first value is returned.

I would like to work with @jeremy-w on a PR to address this (during our testing pair time) but first I need some guidance on what should the behavior be. In my gut I think we should reject the JSON as invalid, and should they want to accept the faulty JSON tell them to pass in `NSJSONSerialization` as the parser.

**Comment by fbartho** [comment]
I certainly would expect the strategy of `latest wins` from other libraries.

**Comment by jgallagher** [comment]
Sounds like collective agreement. :+1:
