### ISSUE TITLE
How to iterate through a dictionaries values

### ISSUE THREAD

**Issue by jcampbell05** [bignerdranch/Freddy#119]
I have a dictionary like this

[
 "identifier": [ "key": "value"],
 "identifier": [ "key": "value"],
 "identifier": [ "key": "value"],
 "identifier": [ "key": "value"]
]

I want to be able to iterate the values of this dictionary so I can parse the sub-dictionaries. How would I do this. So far I've tried this:

```swift
let chatSessionList = try value.dictionary("sessions", or: [:])
        chatSessions = try chatSessionList.map {
            _, value in
            return try UserChatSession.init(json: value)
        }
```

With no luck.

**Comment by randomstep** [comment]
@jcampbell05 do you have some sample data? The dictionary you mention above is in Swift, not JSON, and is invalid since it has the same identifier multiple times.

**Comment by jcampbell05** [comment]
Was an example :) I was only able to iterate thorough by using .lazy.map :)

**Comment by randomstep** [comment]
Sorry, really not clear on what you're asking. You want to treat an array like a dictionary and loop through all values, ignoring the keys?
