### ISSUE TITLE
UnicodeEscapeInvalid on parsing JSON

### ISSUE THREAD

**Issue by siuying** [bignerdranch/Freddy#122]
When parsing a JSON from Twitter, I receive error ``UnicodeEscapeInvalid(119773)``

[list2.json.zip](https://github.com/bignerdranch/Freddy/files/119414/list2.json.zip)

**Comment by randomstep** [comment]
Thanks for reporting this! We are seeing the error.

**Comment by siuying** [comment]
awesome! :confetti_ball:
