### ISSUE TITLE
Default behavior in JSONDecodable implementation

### ISSUE THREAD

**Issue by getaaron** [bignerdranch/Freddy#126]
My suggestion may currently be impossible in Swift, but I'm not 100% sure.

Consider this example from the blog post:

```
extension Message: JSONDecodable {
    public init(json: JSON) throws {
        content = try json.string("content")
        isRead = try json.bool("read")
    }
}
```

This is lots of repetitive boilerplate code. It would be nicer if Freddy provided a default implementation of `JSONDecodable` that, for example:

- traverses the JSON
  - notices the key `content`
    - figure out it’s a string
      - checks if there’s a `[var/let] content: String[?]`
      - sets it
  - notices the key `read`
    - figure out it’s a bool
      - checks if there’s a `[var/let] read: Bool[?]`
      - since there isn't, checks if there’s a `[var/let] isRead: Bool[?]`
      - sets it

Much of this could be accomplished with Swift's `Mirror`, but I don't see a way to actually set the property. Setting can be done with the Objective-C runtime, but that's no fun, and it would remove the ability to use a `struct`.

Does anyone know of a way to implement this? I'm happy to open a PR if this is possible.

**Comment by zwaldowski** [comment]
This can't actually be accomplished with `Mirror` yet, no. It can potentially do the other side (an automatic implementation of `JSONEncodable`), but `Mirror`s aren't writable by design. As you note, writable `struct`s are are orthogonal to `Mirror` because `Mirror` is created with a copy of a value type.

**Comment by getaaron** [comment]
Would you be interested in a PR that implemented it for `JSONEncodable`? Less useful to be sure, but might be a fun exercise.

**Comment by mdmathias** [comment]
Sure!

**Comment by zwaldowski** [comment]
I experimented with it [on a branch](https://github.com/bignerdranch/Freddy/commits/zwaldowski/experimental-magic), you're absolutely welcome to look at it from there. I wasn't able to get performance to a place felt comfortable with it.
