### ISSUE TITLE
Raw value

### ISSUE THREAD

**Issue by ricardopereira** [bignerdranch/Freddy#127]
I tried to extract the raw value of `request-body` with `string()` but it throws an `Freddy.JSON.Error.ValueNotConvertible`.

```swift
let json = try! JSON(data: data)
let itemsRaw = try! json.string("request-body")
let items = try! json.dictionary("request-body")
```

I think it would be a good feature to add a `raw()` function for those cases.
What do you think?

**Comment by randomstep** [comment]
What type is the value of request-body - looks like a dictionary? Why do you want it as a string instead of letting Freddy parse it for you into a dictionary?

**Comment by jeremy-w** [comment]
The `json.string` function is a way to say "decode the value for this key, ensure it is a JSON String, and hand me the Swift String". Those methods do double-duty as schema sanity checking ("I expected a string here, if it's something else, lemme know") and lookup functions ("and if it is a string, can I have it, please?").

Raw access could be obtained already before parsing into Freddy.JSON by working with the NSData you provided to the library without any change to the framework. Perhaps that will suit for you?

**Comment by ricardopereira** [comment]
@randomstep Yes, it is a dictionary. It is a way to extract a piece of json, e.g., to add on the HTTP Body.

@jeremy-w Working with the NSData?! Ok, I will check.

Thank you all.

**Comment by jeremy-w** [comment]
For tacking a chunk onto the HTTP body, you should be able to do something like:

```swift
let requestBodyData = try json.dictionary("request-body").serialize()
responseBody.appendData(requestBodyData)
```
