### ISSUE TITLE
Treat missing OR Null as nil

### ISSUE THREAD

**Issue by markkrenek** [bignerdranch/Freddy#128]
What if an incoming value in some JSON might be missing or might be Null. How do I allow both of those to be treated as nil. There are ifNotFound: and ifNull: variants of the subscripting functions, but I'm not sure how to allow both.

**Comment by randomstep** [comment]
Good question. Perhaps we should expose API for this. Looks like they share some implementation anyway:
```
    private func optionalAtPath(path: [JSONPathType], ifNotFound: Swift.Bool) throws -> JSON? {
        do {
            return try valueAtPath(path, detectNull: true)
```

**Comment by AquaGeek** [comment]
+1 on being able to do this.

**Comment by siyusong** [comment]
Hi all,

I implemented this feature in pull request #141. Please take a look if you are interested.

**Comment by lyricsboy** [comment]
I encountered this when consuming an API that sometimes returned `null` and sometimes the field was absent.

My solution was notably simple: just use `try? json.string("whatever")` and the error is ignored.

**Comment by randomstep** [comment]
Elegant, but that `try?` means any errors would be ignored, not just nil. 

We talked about it internally, and sounds like OptionSet might be a good approach to re-working this API. It is pretty solvable client-side but I think I'd like to see us add API for it.
