### ISSUE TITLE
From JSON to NSData?

### ISSUE THREAD

**Issue by lucatorella** [bignerdranch/Freddy#129]
Let's suppose I've a class `MyStruct` that conforms to the `JSONEncodable` and protocol. With the `toJSON()` method I can create a `Freddy.JSON` value, but how can I get a `NSData`/`String` from that? I'd like a `NSData`/`String` that can be used by the `JSONDecodable` protocol. 

I tried `myStruct.toJSON.description` but the string returned contain escape chars and can't be converted back.

**Comment by randomstep** [comment]
Are you looking for `serialize`?

**Comment by jeremy-w** [comment]
We should probably migrate [these tests](https://github.com/bignerdranch/Freddy/blob/5ef8c74698125a4dd52701b7a597696ef672139e/Tests/JSONSubscriptTests.swift#L45-L73) for serialize over to either JSONEncodableTests.swift or a new SerializeTests file.

A serialize then deserialize and compare for equality test with an equatable, JSONEncodable struct would also be a nice self-contained example of using the framework as well as a good sanity-check test.

**Comment by lucatorella** [comment]
@randomstep Yes, you should add `serialize` to the documentation 🙃 I tried to find it in the code, but I was looking at the wrong file. Thanks.

**Comment by mdmathias** [comment]
@lucatorella is this the [documentation](http://bignerdranch.github.io/Freddy/Enums/JSON.html#/s:FO6Freddy4JSON9serializeFS0_FzT_CSo6NSData) that you are looking for?

**Comment by jeremy-w** [comment]
That looks good to me @mdmathias, but a quick skim of the README led me to
think it focused entirely on deserialization rather than serialization,
which explains the trouble finding that half of the de/serialization
process. :)

--
Jeremy W. Sherman <jeremy@bignerdranch.com>

2016-02-11 12:48 GMT-05:00 mdmathias <notifications@github.com>:

**Comment by randomstep** [comment]
@lucatorella Thanks for the suggestion.

**Comment by randomstep** [comment]
I'm not seeing a link to the generated docs in the README either.

**Comment by jeremy-w** [comment]
@randomstep Please add one. There's a link to the wiki, but we should also link to the docs right alongside it.
