### ISSUE TITLE
From JSON to json String

### ISSUE THREAD

**Issue by lucatorella** [bignerdranch/Freddy#132]
Sometimes it could be useful to have the string version of the json. If I'm not wrong, the only way is using `serialize()` get an `NSData` and then get a `String` back. Does it make sense to create a method to return a string representation?

**Comment by randomstep** [comment]
#127 discussed this a bit. Yes, serialize and then get the string back. What's the use case?

**Comment by lucatorella** [comment]
It's a quite complicated scenario, where I need to create a JSON and pass it back to JavaScript via `evaluateJavaScript`

**Comment by mdmathias** [comment]
#177 addresses this request. We'll be taking a look at that this week.

**Comment by lucatorella** [comment]
Great! 👍
