### ISSUE TITLE
Dictionary: JSONEncodable

### ISSUE THREAD

**Issue by snown** [bignerdranch/Freddy#135]
I have an extension to Dictionary that serves my purposes pretty well of making the `Dictionary` type conform to `JSONEncodable`. However, I can't quite figure out how to make it accept dictionaries with `Optional` value types.

``` swift
extension Dictionary: JSONEncodable {
    public func toJSON() -> JSON {
        var convertibleDictionary: [String: JSON] = [:]
        for (key, value) in self {
            // TODO: Figure out a way to support Optionals
            if let value = value as? JSONEncodable {
                convertibleDictionary[String(key)] = value.toJSON()
            } else {
                return JSON.Null
            }
        }
        
        return JSON.Dictionary(convertibleDictionary)
    }
}
```

Any ideas? Or am I going about this entirely the wrong way?

Thanks.

**Comment by mdmathias** [comment]
`Dictionary` already has an extension to conform to `JSONEncodable`.  [Take a look](https://github.com/bignerdranch/Freddy/blob/master/Sources/JSONEncodable.swift#L29).

Are you trying to call `toJSON()` on a `Dictionary` that has `nil` values inside of it?

E.g.,

```swift
let larry: Person? = nil
let lucinda: Person? = Person(name: "Lucinda")
let people: [String: Person?] = ["larry": larry, "lucinda": lucinda]
let peopleJSON = people.toJSON()
```

Does this example match what you're looking for?  What are you expecting `peopleJSON`'s type to be?

**Comment by snown** [comment]
Close, but what I've really got is a JSON model that looks something like this:
``` JSON
"entity": {
    "id": 12345,
    "sets": [
        {
            "self": "/me",
            "categories": "/channel/explore/1",
            "trending": "/channel/trending/1"
        },
        {
            "self": "/you",
            "sections": "/channel/sections",
            "unpopular": "/channel/unpopular"
        }
    ]
}
```

and what I would like to do is something like this:

``` Swift
struct Entity {
    let id: Int
    var sets: [[String: String]] = []
}

let json: JSON = entity.sets.toJSON()
```

but when you do that it says that `[String: String]` doesn't conform to JSONEncodable. Which if you look at it, it doesn't it has the requisite method, but doesn't actually conform to `JSONEncodable`. It seems you can't have extensions that contain constrictions AND inheritance. So you can't specify a Dictionary extension like this:
``` Swift
extension Dictionary: JSONEncodable where Value: JSONEncodable {
    ...
}
```

Does that make sense?

**Comment by mdmathias** [comment]
Why not make a type for "sets" that conforms to `JSONEncodable`?

So, then you would have:

```swift
struct Entity {
    let id: Int
    let sets: [WhateverTheThingIsNamed]
}
```

**Comment by jgallagher** [comment]
Definitely makes sense, and it is quite unfortunate! I don't think I would solve this problem by making all `Dictionary`s conform to `JSONEncodable`, though, since you have to have some workaround for non-encodable things. (You used inserting `null`; I probably would've defaulted to skipping them entirely, but neither is demonstrably "right".)

To solve your specific problem, I'd either work around the lack of `JSONEncodable`; e.g.,

```swift
let json: JSON = .Array(entity.sets.map { $0.toJSON() })
```

or do like @mdmathias suggested and create a new type to wrap up the sets. That new type could be as dumb as "a struct that contains a dictionary":

```swift
struct EncodableDictionary<Value: JSONEncodable> : JSONEncodable {
    var d: [String : Value]

    func toJSON() -> JSON {
        return d.toJSON()
    }
}
```

**Comment by snown** [comment]
I was thinking the same thing, but that type is genuinely a Dictionary. There are not standard properties to a "set". I tried to show that in the code above by providing different keys in the two sets, but I should have probably called that out specifically.

Additionally you could imagine a similar situation where the dictionary was nested deeper than a single level, so perhaps it's an array of arrays of dictionaries, or something... (I know this sounds like a weird edge case)

**Comment by snown** [comment]
@jgallagher You're right, I don't think returning `JSON.Null` is necessarily the right answer, which is why I don't think this functionality should be in the actual Freddy source until a better solution can be found. However, in my case returning `JSON.Null` works.

I think you made an excellent point, to just use `map`. then I can handle the weirdness of this situation in a closure.

**Comment by mdmathias** [comment]
Is this issue ready to close?

**Comment by mdmathias** [comment]
Closing due to discussion above.
