### ISSUE TITLE
Crash if number is greater than Int.max

### ISSUE THREAD

**Issue by lucatorella** [bignerdranch/Freddy#136]
I'm experiencing a crash while decoding a JSON string containing an int bigger than `Int.max`. You can add the following test to reproduce it.

```
func test() {
  var myJSON = try? JSON(jsonString: "{\"id\":9223372036854775808}")
}
```

Should the library allow bigger ints? If not it should throw an exception instead of crashing.

**Comment by randomstep** [comment]
Related: #76

**Comment by jeremy-w** [comment]
NSJSONSerialization appears to use NSDecimalNumber in this scenario.

**Comment by jgallagher** [comment]
@lucatorella The front-running suggestion in the discussion on #76 would be to make bigger-than-`Int.max` numbers accessible as `String`s, at which point you could parse it into a decimal number yourself or just store it as a string. What are you hoping to do with ints of that size?

**Comment by lucatorella** [comment]
Well actually it was a bug and I wasn't expecting such a big int. Anyway, I'm not sure that crashing is a good option, since it is valid json. I read #76 and I see that there are performance implications in handling this more properly.

**Comment by jgallagher** [comment]
Sure, there's no question that crashing is wrong. :) It's better than handling it incorrectly somehow, though.

The problem is what to do with it since it can't be represented as an `Int`. It sounds like in your case it doesn't matter, since you don't have to deal with it after fixing the bug?

**Comment by lucatorella** [comment]
Yes exactly I'm not affected, and sure it's better than handling it incorrectly

**Comment by jgallagher** [comment]
Cool. Closing this in favor of #76 then, since there's much more discussion there.
