### ISSUE TITLE
Mapping a function over entire JSON

### ISSUE THREAD

**Issue by lucamot** [bignerdranch/Freddy#145]
Hi,
 I'm wondering if it's possible/already implemented to map a function to every leaf element of a JSON. For example, given a simple JSON like this:

```json
{
"dict1": {
    "nest1": {
      "string": "a string",
      "int": 3
    },
    "nest2": {
      "string": "another string",
      "int": 4
    }
  }
}
```

Is it possible with map() or something similar to change, for example, every string by, say, appending "_processed" to it or adding 1 to every integer found?

Of course the given JSON is just an example, in this case I could directly access ("dict1", "nest1", "string") and so on to change the values, I'm interested in a general approach to this problem.

Thanks!

**Comment by jgallagher** [comment]
Freddy doesn't currently have support for modifying a JSON value in-place - its main focus is going in between JSON and model types.

You could write something that took a `JSON` and applied the transformations you described by recursively walking through the entire document:

```swift
extension JSON {
    // add 1 to integers and append "_processed" to non-key strings
    func myModifier() -> JSON {
        switch self {
        case let .Array(values):
            return .Array(values.map { $0.myModifier() })
        case let .Dictionary(d):
            var newDict: [Swift.String : JSON] = Swift.Dictionary(minimumCapacity: d.count)
            for (k, v) in d {
                newDict[k] = v.myModifier()
            }
            return .Dictionary(newDict)
        case let .Int(x):
            return .Int(x + 1)
        case let .String(s):
            return .String(s + "_processed")
        case .Double, .Bool, .Null:
            return self
        }
    }
}
```

Of course this could be generalized to apply other transformations without hardcoding these particular ones.

**Comment by lucamot** [comment]
Yes, I imagined that the framework was more model oriented and I had already coded a solution similar to the one you posted, even though the solution involving the JSON extension is way more elegant than mine. I was just wondering if there were a more 'swiftly' solution to this, maybe using something functional like map() or filter() but I think I can live with this :)

Anyway, thanks for your time and help!
