### ISSUE TITLE
Encoding nested collections: trivial for NSJSON, impossible for Freddie

### ISSUE THREAD

**Issue by schwa** [bignerdranch/Freddy#147]
import Freddie

	let o = [100, [100, 100]]

	// succeeds
	try NSJSONSerialization.dataWithJSONObject(o, options: NSJSONWritingOptions())

	// fails
	o.toJSON()

	//    Playground execution failed: /var/folders/17/8j8f_ktx5rqgpcn2mywh18940000gn/T/./lldb/94263/playground167.swift:11:3: error: type 'NSObject' does not conform to protocol 'JSONEncodable'
	//    o.toJSON()
	//      ^

**Comment by schwa** [comment]
An even simpler problem: ```[1, "test"].toJSON()```

**Comment by jgallagher** [comment]
There are two issues with how you're trying to do what you're trying to do:

* `toJSON` is to convert model object things into Freddy's `JSON` type, but `NSJSONSerialization.dataWithJSONObject` is for turning a JSON thing into an NSData. Freddy's equivalent of that is `serialize`.
* Nested, heterogenous objects become plain `NSObject` in Swift, so there's very little Freddy can do to support them in a type-safe way.

That said, you can use Freddy's support for literals to do both the things you're trying to do:

```swift
// Note the explicit type on o
let o: JSON = [100, [100, 100]]
let data = try o.serialize()

// Using an initializer also works
try JSON([1, "test"]).serialize()
```
