### ISSUE TITLE
Use `JSONEncodable` for literal syntax

### ISSUE THREAD

**Issue by zwaldowski** [bignerdranch/Freddy#150]
A suggestion from [Twitter](https://twitter.com/DeFrenZ/status/712757694797586432):

> why not use JSONEncodable for literal collections convertibles? It would allow nicer usage

By this, he means making the [collection literals](https://github.com/bignerdranch/Freddy/blob/master/Sources/JSONLiteralConvertible.swift#L11-L45) take any `JSONEncodable` protocol type (which includes `JSON` itself) as a member of a collection literal.

I don't think this is unreasonable! This might be one of those "make your Swift compile times incredibly long with this one weird trick!" things but it's worth a shot.

**Comment by zwaldowski** [comment]
Worked on this a few weeks ago and forgot to update with progress. Major roadblock, sadly: `nil` doesn't correspond to any `JSONEncodable`, so this would be a regression in that area.

**Comment by DeFrenZ** [comment]
Yes, I explored the idea as well and came to the same conclusion. There would be a big drawback in not being able to use the `nil` literal anymore, unluckily :\

**Comment by zwaldowski** [comment]
A potential idea to use a "lifting" operator  for instances of `JSONEncodable` [came up on Swift-Evolution](https://lists.swift.org/pipermail/swift-evolution/Week-of-Mon-20160411/014941.html):

```swift
prefix operator ^ {}
prefix func ^ <Value: JSONEncodable> (value: Value) -> JSON {
		return value.toJSON()
}
	
let json: JSON = ["foo": [2.0, nil], "bar": ^myValue]
```

This isn't something I recommend or prefer whatsoever, but it's a potential solution. We could also add/restore a `JSON.init<T: JSONEncodable>(_:)`. Neither are as nice as having it work with the literal, though.

**Comment by jeremy-w** [comment]
@zwaldowski What is the outcome of this? Close as unworkable, remove from 2.1 and kick down the road, or something else?

**Comment by zwaldowski** [comment]
Kicked can. We need to cull the Future milestone after we get this next release out.
