### ISSUE TITLE
Quick existence check

### ISSUE THREAD

**Issue by victor** [bignerdranch/Freddy#157]
I need to check for the existence of a given key on the root level of a JSON object.
I know I can use `if let dataArray = myJson.array("data", ifNotNotFound: true)` to get a nil if the key I'm looking for does not exist, and check I am getting something with the `if let`.
But that feels too convoluted, I feel that there should be a quicker way of either checking for the existence of a key, or getting a list of the keys a root json object has, so that I can do the lookup myself.
However I found nothing to do that.
Is there a way, or am I approaching the problem the wrong way?

thanks

**Comment by jgallagher** [comment]
It's hard to say if you're approaching the problem the wrong way without knowing more about why you're trying to do this. I don't think we've ever needed to check for the existence of a key without subsequently needing the value associated with it, so there's nothing directly in Freddy to do this kind of check. You can, however, get the top level object as a dictionary and then do normal Swift dictionary things (like get a collection of the keys); e.g.,

```swift
let myJsonRoot = try myJson.dictionary()

if myJsonRoot.keys.contains("data") {
    print("we have a `data` key")
}
```

**Comment by victor** [comment]
There's certainly reasons to do what I'm asking for. Depending on the existence of some keys, others may mean different things. I agree it's not usual, but sometimes you get this from APIs.

I tried doing before what you suggested and for some reason I was getting an error. I tried again now and it worked, so that's what I'll be doing. I'll chalk it to being related to the fact that I was using it in a playground.

Thanks again
victor

**Comment by jgallagher** [comment]
> it's not usual, but sometimes you get this from APIs

story of my life 😂

**Comment by victor** [comment]
I noticed that I also can do `if myJsonRoot["data"] != nil`. It was on the Subscripting doc but I missed it, and it seems it's not recommended. How likely am I to shoot myself on the foot with it?

**Comment by jgallagher** [comment]
The docs for subscripting like that is phrased the way it is because it's usually worse than the `dictionary()`/`string()`/etc. methods for two reasons:

* You lose any error information since it returns `JSON?` instead of `throws -> JSON`
* Nested objects are somewhat more verbose to drill down into

but neither of these affects this specific use case (just checking for the existence of a key). Should be fine. 👍
