### ISSUE TITLE
Make a utility method which decodes a value as an NSDecimalNumber instead of a Double

### ISSUE THREAD

**Issue by rhinoid** [bignerdranch/Freddy#164]
At the moment I can parse a value to a Double:

let amount = try value.double("amount")

But when this amount is e.g.: 144.77, Freddy parses it to: 144.76999999999998 which is correct.
However, to not introduce these rounding errors I'd prefer to have an option to parse it to an NSDecimalNumber. Something like:

let amount = try value.decimal("amount")

Perhaps an even better solution would be to configure Freddy to use NSDecimalNumbers instead of Doubles when parsing a payload. I've heard that this is how it's done on Android (Where they have BigDecimal)

**Comment by zwaldowski** [comment]
Freddy is in maintenance mode and looking only to make bug fixes right now. We understand that this may be useful in certain scenarios, and welcome pull requests. Thanks for your suggestion.
