### ISSUE TITLE
Capture Path in parsing errors

### ISSUE THREAD

**Issue by paulhimes** [bignerdranch/Freddy#165]
It would be helpful when debugging to know which path caused an error. If, for example, the following code generates a ValueNotConvertible error:

`let key = try json.string("key")`
`let nickname = try json.string("nickname")`

The error only prints out: ValueNotConvertible(null, Swift.String). This tells us that a value we thought was a String is in fact null. It would be nice if it would also tell us _which_ value was null.

Currently, we can achieve this by wrapping each line in its own "do" block, but that adds a lot of extra boilerplate.

**Comment by krpiatkowski** [comment]
The full path into the failing value would be nice as well

eg a.b[1].c

**Comment by zwaldowski** [comment]
We understand how useful this would be. Freddy is currently in maintenance mode and only seeking to make bug fixes. You may find better debuggability through `Codable`.
