### ISSUE TITLE
Does the JSON type implements COW(copy of write)?

### ISSUE THREAD

**Issue by soapsign** [bignerdranch/Freddy#169]
According to official swift optimization tips [here](https://github.com/apple/swift/blob/master/docs/OptimizationTips.rst#advice-use-copy-on-write-semantics-for-large-values). The structure of JSON seem will suffer from this performance problem when passing as argument . I wonder does JSON have implemented COW?

**Comment by jgallagher** [comment]
`JSON` actually already does (coincidentally) exactly what that link suggests as the first option:

> The easiest way to implement copy-on-write is to compose existing copy-on-write data structures, such as Array.

Each of `JSON`'s cases is either a COW type itself (array, string, or dictionary) or is a small value type for which COW is unnecessary.
