### ISSUE TITLE
dictionaryOf() for JSON objects with a specific type of children?

### ISSUE THREAD

**Issue by cpboyd** [bignerdranch/Freddy#171]
I have a JSON object that's similar to:
```json
{
  "people": {
    "123":{"name":"Jane Doe", "age":35},
    "124":{"name":"John Doe", "age":37}
  }
}
```

Currently, my code to parse this is:
```swift
        people = Dictionary()
        if let temp = try value.dictionary("people", alongPath: options) {
            for (key, value) in temp {
                people![key] = try? Person(json: value)
            }
        }
```

Where Person implements JSONDecodable:
```swift
public struct Person {
    public let name: String
    public let age: Int
}

extension Person: JSONDecodable {
    public init(json value: JSON) throws {
        name = try value.string("name")
        age = try value.int("age")
    }
}
```

With arrays, there exists ```arrayOf()``` which nicely maps the JSON objects to the values.

Is there a similar way (more efficient than my method) to get a Dictionary of Person objects?

I'd like to maintain the key/value method of associating with a specific object, as the key links them to other data.

Thanks.

**Comment by jgallagher** [comment]
I don't think there's (currently) a significantly more efficient way to do what you're doing, as `map` on a Swift dictionary returns an array of tuples, not a new dictionary, so implementing `dictionaryOf` would require nearly the exact same loop you have written above. One small difference that could speed things up if your dictionaries are large is to use the `Dictionary(minimumCapacity:)` initializer to avoid excessive reallocation internally; e.g.,

```swift
        if let temp = try value.dictionary("people", alongPath: options) {
            people = Dictionary(minimumCapacity: temp.count)
            for (key, value) in temp {
                people![key] = try? Person(json: value)
            }
        }
```

**Comment by cpboyd** [comment]
@jgallagher Ah, ok.  Thanks!

I'm still new to Swift, so I wasn't sure if there might be a more optimized way to do this.
