### ISSUE TITLE
Is there a concise way to decode a nested dictionary that may be null

### ISSUE THREAD

**Issue by timrozum** [bignerdranch/Freddy#173]
Here is example JSON when the nested dictionary, "engine", is not null:

```
{
  "color" : "Red",
  "engine" : {
    "cylinder_count" : 8,
    "horsepower" : 300
  }
}
```

And here is example JSON when "engine" is null:

```
{
  "color" : "Red",
  "engine" : null
}
```

Here is the Engine model which works fine:

```
struct Engine: JSONDecodable {
  let cylinderCount: Int
  let horsepower: Int
  
  init(json: JSON) throws {
    cylinderCount = try json.int("cylinder_count")
    horsepower = try json.int("horsepower")
  }
}
```

And here is the Car model which also works fine but it seems like there should be a more concise way to handle the engine parsing:

```
struct Car: JSONDecodable {
  let color: String
  let engine: Engine?
  
  init(json: JSON) throws {
    color = try json.string("color")

    if let _ = try json.dictionary("engine", alongPath: [.NullBecomesNil]) {
      engine = try json.decode("engine", alongPath: [.NullBecomesNil])
    } else {
      engine = nil
    }
  }
}
```

I thought this would work:

```
struct Car: JSONDecodable {
  let color: String
  let engine: Engine?
  
  init(json: JSON) throws {
    color = try json.string("color")

    engine = try json.decode("engine", alongPath: [.NullBecomesNil])
  }
}
```

But it results in the error "Freddy.JSON.Error.UnexpectedSubscript(Swift.String)".

Am I missing something?  Is there a better way to handle this situation?  

Thank you very much, there are a lot of things I like about the framework!

**Comment by jgallagher** [comment]
This is a tricky one. The reason

```swift
struct Car: JSONDecodable {
  let color: String
  let engine: Engine?

  init(json: JSON) throws {
    color = try json.string("color")

    engine = try json.decode("engine", alongPath: [.NullBecomesNil])
  }
}
```

doesn't work as you expect is that the `alongPath` argument modifies keys along the path you have specified in that call to decode. In your case that entire path is `"engine"`, and the `engine` key _does_ exist in your JSON. Freddy therefore pulls out the value (`null`) and hands that to your `Engine.init`. The error you're seeing is being thrown from your initializer since `null` doesn't contain the `cylinder_count` or `horsepower` keys.

This isn't much cleaner, but you could avoid double-decoding by passing the dictionary you get back directly to `Engine.init`:

```swift
struct Car: JSONDecodable {
  let color: String
  let engine: Engine?

  init(json: JSON) throws {
    color = try json.string("color")

    if let engineDictionary = try json.dictionary("engine", alongPath: [.NullBecomesNil]) {
      engine = try Engine(json: .Dictionary(engineDictionary))
    } else {
      engine = nil
    }
  }
}
```

@zwaldowski / @mdmathias Do we have a better solution for this I'm not seeing? Is this a case for perhaps another kind of `SubscriptingOption` (`TerminatingNullBecomesNil` or something)?

**Comment by mdmathias** [comment]
I can't think of something cleaner or doesn't throw away errors off the top of my head. 

Do we need another `SubscriptingOption`? Or, could the behavior be the same as `json.dictionary(_,alongPath:)`? That is, if `decode` should find a `JSON.Null` at `path`, and nulls are to become nil, then we should catch that and return nil as we do now. It seems reasonable to me to say that a null is not convertible to an `Engine`. 

The benefit there is that there is no addition to the options. The con is that I have not looked at how to do that yet so it could be brainless. :/

Is there a good reason to say that these are different cases that I'm not seeing?

**Comment by justbaum30** [comment]
We ran into this issue on our project as well. We made the following change, not sure if there is a better way of doing it...

```swift
private func mapOptionalAtPath<Value>(path: [JSONPathType], alongPath: SubscriptingOptions, @noescape transform: JSON throws -> Value) throws -> Value? {
    let detectNull = alongPath.contains(.NullBecomesNil)
    let detectNotFound = alongPath.contains(.MissingKeyBecomesNil)
    var json: JSON?
    do {
        json = try valueAtPath(path, detectNull: detectNull)
        if json == .Null && detectNull { // Added this check to bail if detecting null
            return nil
        } else {
            return try json.map(transform)
        }
    } catch Error.IndexOutOfBounds where detectNotFound {
        return nil
    } catch Error.KeyNotFound where detectNotFound {
        return nil
    } catch Error.ValueNotConvertible where detectNull && json == .Null {
        return nil
    } catch SubscriptError.SubscriptIntoNull where detectNull {
        return nil
    }
}
```

**Comment by timrozum** [comment]
Thanks for the info.  This is what is confusing to me, or I guess seems inconsistent.  Let's say that `color` may be null.  In that case the code below works great and just as I would expect.  So if the value of color is null it returns nil.

`color = try json.string("color", alongPath: [.NullBecomesNil])`

Now if the `color` key may not exist it makes sense to me that I should use `[.MissingKeyBecomesNil]`.

So decoding a string like above seems very intuitive and provides control over handling a missing key in the path and handling a null end result value.  So I expected `.decode` to behave similarly and be able to handle a null end result value but that is not the case.  This situation isn't uncommon for us so having an elegant way to achieve this would be great.

**Comment by timrozum** [comment]
I tried out this fix and it works great for me!  Thank you very much!
