### ISSUE TITLE
Code signing error with Mac build

### ISSUE THREAD

**Issue by glennrfisher** [bignerdranch/Freddy#175]
I'm having trouble building the Mac target of Freddy with Carthage. The problem seems related to the code signing identity for the Mac target. Any help would be much appreciated! :)

Here's my `Cartfile`:

```
github "bignerdranch/Freddy"
```

Here's the console log:

```
macbook-pro-3:Freddy glennfisher$ carthage update
*** Fetching Freddy
*** Checking out Freddy at "2.1.0"
*** xcodebuild output can be found in /var/folders/dg/zqb957lx6dq4hjhb80s7plvc0000gn/T/carthage-xcodebuild.axWCQu.log
*** Building scheme "Freddy" in Freddy.xcodeproj
*** WARNING: Skipping build for "macosx" SDK because the necessary signing identity "-" is not installed
*** Building scheme "NanoFreddy" in Freddy.xcodeproj
*** Building scheme "TVFreddy" in Freddy.xcodeproj
*** Building scheme "MobileFreddy" in Freddy.xcodeproj
```

**Comment by zwaldowski** [comment]
Hmmm. I'm not sure what Carthage is doing that our normal `xcodebuild` invocations on Travis aren't. The [null code signing](https://github.com/bignerdranch/Freddy/blob/master/Configurations/Base.xcconfig#L42) identity is the right thing to do… and works fine in our [other frameworks](https://github.com/bignerdranch/Deferred/blob/master/Configurations/Base.xcconfig#L42). Strange.

**Comment by glennrfisher** [comment]
Strange indeed. I went into the Xcode preferences and created a signing identity for Mac development, but I still see the same error.

I'm still generally confused about code signing. Can you explain why the `-` code signing identity is the right one to use? I've seen other repositories specify `Don't Code Sign` which has seemed to resolve similar problems in the past (Carthage/Carthage#897).

I may play around with the code signing settings in a fork and see if I can't get that to build with Carthage.

Thanks for your help! It's very appreciated. :)

**Comment by glennrfisher** [comment]
Ah... I think I found the problem. It looks like I was using an older version of Carthage. I updated to the most recent release and can now build the Mac target for `Freddy` just fine.

Thanks for your help!
