### ISSUE TITLE
Swift 2.3 support

### ISSUE THREAD

**Issue by mz2** [bignerdranch/Freddy#179]
Looks like there are a few compilation failures when compiling with Swift 2.3.

**Comment by zwaldowski** [comment]
You might've been building with the Swift 3 compiler. See also #180.

**Comment by mz2** [comment]
Ah, quite possible.

**Comment by siuying** [comment]
How about Swift 3?

**Comment by mz2** [comment]
See https://github.com/bignerdranch/Freddy/tree/swift3

**Comment by indrajitsinh** [comment]
@mz2  try following in your Cartfile

github "bignerdranch/Freddy" ~> 2.1
