### ISSUE TITLE
Is there a concise way to decode a nested array that may be null

### ISSUE THREAD

**Issue by timrozum** [bignerdranch/Freddy#181]
This issue is very similar to #173 except instead of a nested dictionary it is a nested array.  I just ran into a real situation where I needed to do this.

For my example lets pretend that cars can have multiple engines.  :)

Here is the JSON when the `engines` array is not null: 

```
{
  "color" : "Red",
  "tires" : null,
  "engines" : [{
               "cylinder_count" : 8,
               "horsepower" : 300
               },
               {
               "cylinder_count" : 8,
               "horsepower" : 300
               }
  ]
}
```

Here is the JSON when the `engines` array is null:

```
{
  "color" : "Red",
  "tires" : null,
  "engines" : null
}
```

And here is the parsing code:

```
struct Car: JSONDecodable {
  let color: String
  let engines: [Engine]?
  let tires: String?
  
  init(json: JSON) throws {
    color = try json.string("color")

    // I think this is the only way to handle an array that may be null
    do {
      engines = try json.array("engines").map(Engine.init)
    } catch JSON.Error.ValueNotConvertible {
      engines = nil
    }
    
    // It would be nice if this worked but it does not compile
//    engines = try json.array("engines", alongPath: [.NullBecomesNil]).map(Engine.init)
    
    // This is another alternative I hoped would work but also has a compile error
//    engines = try json.decode("engines", alongPath: [.NullBecomesNil])
    
    tires = try json.string("tires", alongPath: [.NullBecomesNil])
  }
}

struct Engine: JSONDecodable {
  let cylinderCount: Int
  let horsepower: Int
  
  init(json: JSON) throws {
    cylinderCount = try json.int("cylinder_count")
    horsepower = try json.int("horsepower")
  }
}
```

See the comments in the code to see what I was able to make work and some alternatives that would be nice if they worked.  There isn't another way to do this is there?  My solution that works isn't great because it's verbose and also it seems like there could be valid ValueNotConvertible errors that go undetected.

Thanks!

**Comment by DarkSatyr** [comment]
What about engines = try? json.array("engines").map(Engine.init)
or 
badges = try? json.arrayOf("engines", type: Engine.self)

**Comment by timrozum** [comment]
@DarkSatyr thank you for the suggestion.  It is concise but if there is a legitimate error that Freddy encounters while parsing, the error would go undetected I think.  It would be ideal to have a concise solution that will not suppress errors.

**Comment by DarkSatyr** [comment]
@timrozum 
What about
engines = try json.array("engines", alongPath: [.NullBecomesNil])?.map(Engine.init)
or 
engines = try json.arrayOf("engines", type: Engine.self)

?

**Comment by timrozum** [comment]
`engines = try json.array("engines", alongPath: [.NullBecomesNil])?.map(Engine.init)` does work which is a big improvement.  It seems intuitive now but it wasn't obvious to me before.  It may be easier for others in the future if somehow the operation didn't require optional chaining or an example like this was documented.  This works very well now that I understand.  Thank you very much for the help!
