### ISSUE TITLE
Symbolic breakpoint crashes app.

### ISSUE THREAD

**Issue by mediumbear** [bignerdranch/Freddy#182]
I've been enjoying Freddy, and have been using a symbolic breakpoint on JSON.Error. However my app started crashing in strange ways. I get an EXC_BREAKPOINT in my main thread in the runloop:
`callq  0x108f85468               ; symbol stub for: getpid`.
I'm using Freddy in another thread. If I look at that thread, it's always halted on a line decoding JSON. If I 'po' the code on this line the JSON decodes normally.  
If I continue running, the main thread receives a SIGKILL.
If I turn off the symbolic breakpoint, the app runs without error.

Has anyone ever experienced this problem? Thanks.

**Comment by lyricsboy** [comment]
Can you provide details of what your breakpoint is doing? Additional stack frames from the main thread?

I have encountered this problem with breakpoints before in projects with no use of Freddy. I think it's an Xcode/LLDB/iOS quirk of some kind, but I've never been able to fully track it down.

**Comment by mdmathias** [comment]
Closing due to lack of information. Please feel free to reopen if this is still an issue.
