### ISSUE TITLE
more complete example

### ISSUE THREAD

**Issue by tcurdt** [bignerdranch/Freddy#184]
Would be nice to have an example in the docs showing this SwiftyJSON equivalent

        string = json["string"].stringValue
        int = json["int"].intValue
        double = json["double"].doubleValue
        float = json["float"].floatValue
        bool = json["bool"].boolValue
        array = json["array"].arrayObject ?? [AnyObject]()
        dictionary = json["dictionary"].dictionaryObject ?? [String: AnyObject]()
        optionalString = json["string"].string
        optionalInt = json["int"].int
        optionalDouble = json["double"].double
        optionalFloat = json["float"].float
        optionalBool = json["bool"].bool
        optionalArray = json["array"].arrayObject
        optionalDictionary = json["dictionary"].dictionaryObject

**Comment by mdmathias** [comment]
Thanks for the feedback. We will look for ways to improve the coverage of our examples and tutorials as we make our way to Freddy's next release. Those docs will have to be updated anyway!

In the meantime, we think that the [README](https://github.com/bignerdranch/Freddy/blob/master/README.md), [Wiki](https://github.com/bignerdranch/Freddy/wiki), [documentation](http://bignerdranch.github.io/Freddy/index.html), and the [intro blog post](https://www.bignerdranch.com/blog/introducing-freddy-an-open-source-framework-for-parsing-json-in-swift/) cover this sort of thing pretty well.

**Comment by mdmathias** [comment]
I should also mention that [Freddy's tests](https://github.com/bignerdranch/Freddy/tree/master/Tests) also include a number of the sort of examples that you mention above. [JSONSubscriptingTests.swift](https://github.com/bignerdranch/Freddy/blob/master/Tests/JSONSubscriptingTests.swift) is especially useful.
