### ISSUE TITLE
JSONFromString() does crash on certain inputs. 

### ISSUE THREAD

**Issue by nst** [bignerdranch/Freddy#199]
**Steps to reproduce**

Run JSONFromString() with the following Swift strings as input:
    
    " "
    "[0,"
    "{\"\":"

**Expected behavior**

Since these strings are invalid JSON according to [RFC 7159](https://tools.ietf.org/html/rfc7159), JSONFromString() should throw an error.

**Actual behavior**

JSONFromString() does crash.

**Comment by jeremy-w** [comment]
Please add a backtrace for the crash and include the version in use.

**Comment by jgallagher** [comment]
Not necessary in this case - crash is trivially reproducible on `master`; fixed in #200.

**Comment by jeremy-w** [comment]
:+1: Thanks @jgallagher & @nst.
