### ISSUE TITLE
Command failed due to signal: Segmentation fault: 11

### ISSUE THREAD

**Issue by DanD21** [bignerdranch/Freddy#202]
guys, Xcode 7.2.1 fail to build JSONParser.swift from Freddy.
Command failed due to signal: Segmentation fault: 11

But it was ok the first day. The second day I opened Xcode, without doing any changes, and this comes up.
Tried to build the project to another computer, Xcode 7.3 is there, and it works perfectly fine!

![screen shot 2016-08-31 at 12 43 53 pm](https://cloud.githubusercontent.com/assets/9061536/18123909/ad09c7d4-6f78-11e6-869e-5d15d099dc69.png)

**Comment by jgallagher** [comment]
Yes, this is unfortunately not surprising - Swift 2.2 / Xcode 7.3 fixed a number of compiler crashers. We do not support Swift 2.1 anymore, although in a pinch you could (potentially) pull in an older Freddy release if you needed to use Xcode 7.2.

**Comment by DanD21** [comment]
yes, that's what I did. Freddy 2.0.1 is woking fine with Xcode 7.2
