### ISSUE TITLE
Swift 2.3 support?

### ISSUE THREAD

**Issue by DarkSatyr** [bignerdranch/Freddy#203]
Hi everyone
Guys, are going to migrate to Swift 2.3 first and then to Swift 3.0, or are you going to move to Swift 3.0 directly?
Other question - When are you going to release Swift 3.0 compatible version? (2.3 if case)

**Comment by zwaldowski** [comment]
`master` is compatible with Swift 2.3. Our current Swift 3 branch is at [`swift3`](https://github.com/bignerdranch/Freddy/tree/swift3).

**Comment by AquaGeek** [comment]
Are there plans to tag a 2.3-compatible release?

**Comment by ratkins** [comment]
(Tagging a Swift 2.3-compatible release would help a lot with Freddy as a Carthage dependency.)

**Comment by tylerarnold** [comment]
I believe there is a 2.3 branch, I am pointing to it in my on my 2.3 project branches podfiles

**Comment by ratkins** [comment]
Ah, right you are—my git-fu is weak and I interpreted the `zwaldoski/swift-2_3` branch name as being an unofficial fork.
