### ISSUE TITLE
JSONFromString() does crash on certain inputs.

### ISSUE THREAD

**Issue by nst** [bignerdranch/Freddy#206]
**Step to reproduce**

Run JSONFromString() with the following Swift string as input:

```
"[\"\\"
```

**Expected behavior**

Since this strings is invalid JSON according to [RFC 7159](https://tools.ietf.org/html/rfc7159), JSONFromString() should throw an error.

**Actual behavior**

JSONFromString() does crash.

**Comment by jgallagher** [comment]
Fixed by #216.
