### ISSUE TITLE
How to read an array of dictionaries?

### ISSUE THREAD

**Issue by kgrigsby59** [bignerdranch/Freddy#211]
I have the following JSON
```
[
  {
    "search": "one",
    "replacement": "1"
  },
  {
    "search": "two",
    "replacement": "2"
  }
]
```
and want to read it into an array of HTMLReplacementCriteria
```
            struct HTMLReplacementCriteria: JSONDecodable {
                let search: String
                let replacement: String
                
                init(json: JSON) throws {
                    search = try json.string("search")
                    replacement = try json.string("replacement")
                }
```
Is there a method on JSON that can take my type (HTMLReplacementCriteria) and return an array of them or must the top level be a dictionary?

**Comment by jgallagher** [comment]
I believe you want `yourJSON.arrayOf(type: HTMLReplacementCriteria.self)`.

**Comment by mdmathias** [comment]
Yep! See the [README](https://github.com/bignerdranch/Freddy#jsondecodable-deserializing-models-directly) and the tests for examples.

**Comment by kgrigsby59** [comment]
@jgallagher Thank You!
@mdmathias I did look in both both places before posting. I don't see any references to 'arrayOf' in the README and the JSONSubscriptingTests.swift only use the arrayOf("residents", type: Resident.self) method. I didn't look closely enough at the arrayOf documentation to see that the first parameter can be omitted.

**Comment by mdmathias** [comment]
@kgrigsby59 The README and the tests give examples of accomplishing the same goal using a variety of approaches. Nonetheless, `arrayOf` is certainly a good way to go!

For example, I linked to the following in the README:

```swift
let data = getSomeData()
do {
    let json = try JSON(data: data)
    let people = try json.array("people").map(Person.init)
    // do something with `people`
} catch {
    // do something with the error
}
```

**Comment by edasque** [comment]
Sorry, I must be missing something but I don't get it. In:
```swift
            let json = try JSON(jsonString: the_jsonString as String)
```

*json* has no array or arrayOf method in Freddy 3.0 AFAIK.

I haven't found how to map a JSON file (to an array of my *StockQuote* structures) when the root of the JSON is an array and not a dictionary. Obviously ```json.decodedArray(at:"")``` does not work.

@mdmathias can you point at what I am missing?
