### ISSUE TITLE
Text representation of a JSON object

### ISSUE THREAD

**Issue by okla** [bignerdranch/Freddy#213]
For example, 
```
let json = ["key" : 1].toJSON()
```
Can I somehow convert `json` to something like this
```
{
  "key" : 1
}
```
to store in a text file?

**Comment by mdmathias** [comment]
You can do something like this:

```swift
do {
    let json = ["key": 1].toJSON()
    let jsonString = try json.serializeString()
    jsonString.writeToURL(url, atomically: true, encoding: NSUTF8StringEncoding)
} catch {
    // handle error
}
```

**Comment by okla** [comment]
Sorry, but I can't find `serializeString()`. (I'm on swift3 branch)

**Comment by mdmathias** [comment]
Ah. Sorry about that confusion. It's on master at the moment. We'll be merging swift3 with master and tagging another release. Today, hopefully.
