### ISSUE TITLE
Convert JSON back to original object

### ISSUE THREAD

**Issue by okla** [bignerdranch/Freddy#217]
```
let array = [1, 2, 3]
let json = array.toJSON()
```
How can I get original array from `json`?

P.S. Sorry for flooding issues. Maybe there's a better place for such dumb questions?

**Comment by mdmathias** [comment]
You could try:

```swift
let array = [1, 2, 3]
let json = array.toJSON()
let arrayAgain = json.decodedArray(type: Int.self)
```

The above uses Freddy 3.0.0 syntax, which will be released momentarily.
