### ISSUE TITLE
Need to update Cocoapods to v3.0

### ISSUE THREAD

**Issue by soheilbm** [bignerdranch/Freddy#220]
Cocoapods.org still show v2.X of Freddy. 
Please push the latest tag to cocoapods too. Thanks.

**Comment by kbduvall** [comment]
Until that's done, you can use 3.0 by defining your Podfile like:
pod 'Freddy', :git => 'https://github.com/bignerdranch/Freddy.git'

**Comment by soheilbm** [comment]
But I'm using this pod as dependency in my podspec. Cannot use branch name in podspec

**Comment by mdmathias** [comment]
Hi there! Freddy should be up to date with version 3.0.0 on CocoaPods now.

https://cocoapods.org/?q=Freddy
