### ISSUE TITLE
enum doesn't conform to expected type 'JSONDecodable'

### ISSUE THREAD

**Issue by okla** [bignerdranch/Freddy#221]
Following code causes error:
```swift
enum Numbers: String {

  case one, two, three
}

// In argument type 'Numbers.Type', 'Numbers' does not conform to expected type 'JSONDecodable'
let number = try? json.decode(at: 0, type: Numbers.self)
```

But if I add 
```swift
extension Numbers: JSONDecodable {}
```
the error's gone.

Shouldn't `Numbers` adopt `JSONDecodable` implicitly?

Swift 3, Xcode 8

**Comment by zwaldowski** [comment]
This is fully intended behavior. We can't make your types conform to `JSONDecodable` for you; we can only provide default implementations for your implementation.

**Comment by okla** [comment]
Ok, thanks!
