### ISSUE TITLE
Integrating issues of Freddy in Xode project.

### ISSUE THREAD

**Issue by codecraver** [bignerdranch/Freddy#226]
Hello, I am brand new to this iOS development This is my first time integrating an external resource into the project. I have tried and  installed your Freddy package  successfully but i am getting lot of build errors in my project after installation. am i doing wrong somewhere? I have set my deployment target as 8.0 and i am using xcode V 7.1 in OS X EI Captain.
Let me know if i need to provide any further information about like what errors i am getting etc.
Few of them are:

```
"Pods/Freddy/Sources/JSONSubscripting.swift:484:66: @autoclosure is now an attribute of the parameter declaration, not its type"
"Pods/Freddy/Sources/JSONSubscripting.swift:22:16: Expected ',' separator"
"Pods/Freddy/Sources/JSONParser.swift:112:25: Thrown expression type 'JSONParser.Error' does not conform to 'ErrorType'"
"Pods/Freddy/Sources/JSONSubscripting.swift:254:30: Value of type 'JSON.SubscriptingOptions' has no member 'contains'"
"Pods/Freddy/Sources/JSONParsing.swift:111:39: Extraneous '_' in parameter: 'jsonArray' has no keyword argument name"
```

I am not sure if i am using any latest versions of swift or something. Please assist, thanks.

And following is my pod file text, thought might be helpful if i did something wrong:

```ruby
#Uncomment this line to define a global platform for your project
#platform :ios, '9.0'
target 'Myapp' do
  #Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Freddy', '~> 3.0'
  #Pods for Eaturbia
end
```

**Comment by davidahouse** [comment]
The 3.0 version of Freddy can only be used with Xcode 8 and Swift 3.0 projects. I would suggest pulling in the previous version of Freddy that is compatible with Xcode 7. To do that, just change the version number for Freddy in your pod file from 3.0 to 2.1.0. For example:

`pod 'Freddy', '~> 2.1.0'`

**Comment by codecraver** [comment]
Thanks Davidahouse, 
installing lower version of Freddy solved many errors but only one issue it is throwing 
**the compilation of JSONParser.swift is failing with an error showing 
Command failed due to signal: Segmentation fault: 11**

**Comment by jeremy-w** [comment]
Sounds like a compiler bug. The recommended fix is to update to a more recent version of Xcode 7. Alternatively, you can try to mutate the code to avoid the segfault, but this can be frustrating and time-consuming.
