### ISSUE TITLE
Podspec update?

### ISSUE THREAD

**Issue by lottadot** [bignerdranch/Freddy#255]
Was the Podspec update in https://github.com/bignerdranch/Freddy/commit/936f73395714850e607e1cbce4f0ee715345ed34 pushed ? 
https://cocoapods.org/pods/Freddy shows 
https://github.com/CocoaPods/Specs/blob/master/Specs/0/1/8/Freddy/3.0.0/Freddy.podspec.json 3.0.0 not 3.0.2

**Comment by YMonnier** [comment]
The Freddy Cocoapods Repo has not been updated: https://cocoapods.org/pods/Freddy (still 3.0.0)

It would be great to have the latest version 3.0.2. 
Currently, I cannot put Freddy as Podspec dependency.

```ruby
s.dependency 'Freddy', '~> 3.0.2'
```

```ruby
[!] Failed to load 'SubModule' podspec:
[!] Invalid `SubModule.podspec` file: [!] Unsupported version requirements.
```

**Comment by mdmathias** [comment]
This should be fixed now. I updated the `.swift-version` file to 3.0 and pushed the Podspec to the Trunk.

https://github.com/bignerdranch/Freddy/pull/257

https://cocoapods.org/pods/Freddy
