### ISSUE TITLE
does not compile with Xcode 9

### ISSUE THREAD

**Issue by dave256** [bignerdranch/Freddy#263]
Freddy does not compile with Xcode 9 (and the conversion to Swift 4 fails). I think I've got it working but I'm not certain everything I've done is correct (although it does pass the unit tests other than the 32 bit overflow which I believe should fail unless run on iPhone 5 simulator). I can make a pull request if you want. Here is my fork/branch: https://github.com/dave256/Freddy/tree/Swift4-Xcode9

**Comment by davidahouse** [comment]
We have 2 PRs up to address Swift 3.2 and Swift 4 issues: #265 & #267. Will close this issue once they are merged. Thanks for creating an issue for this!

**Comment by dave256** [comment]
Are there plans to update with these fixes for Swift 4 or is Freddy being abandoned?

**Comment by dave256** [comment]
@davidahouse somehow it appears I unassigned you. I didn't mean to do that, but it looks like Freddy is being abandoned since it hasn't been updated since last fall.

**Comment by davidahouse** [comment]
@dave256 Yeah looks like all the primary maintainers aren't active anymore. I've moved over to using the builtin JSON improvements in Swift 4 and that seems to work for the things I need it for.

**Comment by dave256** [comment]
@davidahouse thanks for letting me know. I've got a project using Freddy and can't easily move it to the built-in Codable options (basically using protocols to essentially simulate a base "struct" with 3 "subclasses" of struct and reading one property from JSON to then delegate which struct we create) but now I know I can just take Freddy and update it without needing to worry about being able to easily keep it merging cleanly as Freddy is updated. I probably should refactor it to use enums with associated types and then I think I could use the built-in Swift 4 options (although I wonder if Freddy might be faster than the built-in options).
