### ISSUE TITLE
Push 3.0.3 release to cocoapods master repo

### ISSUE THREAD

**Issue by timle8n1** [bignerdranch/Freddy#271]
It seems as Freddy 3.0.3 was released 12 days ago with just pod spec changes, however this pod spec does not appear to have been pushed to the Cocoapods master spec repo

**Comment by paulhimes** [comment]
+1

**Comment by volodg** [comment]
+1

**Comment by GuillaumeVachon** [comment]
+1

**Comment by zwaldowski** [comment]
3.0.3 was pushed this morning: https://cocoapods.org/pods/Freddy
