### ISSUE TITLE
JSONParser.swift uses deprecated API when compiled against Swift 4.1

### ISSUE THREAD

**Issue by alanzeino** [bignerdranch/Freddy#275]
```
JSONParser.swift:187:21: error: 'index(_:offsetBy:limitedBy:)' is deprecated: all index distances are now of type Int
        guard input.index(loc, offsetBy: 3, limitedBy: input.count) != input.count else {
                    ^
JSONParser.swift:202:21: error: 'index(_:offsetBy:limitedBy:)' is deprecated: all index distances are now of type Int
        guard input.index(loc, offsetBy: 3, limitedBy: input.count) != input.count else {
                    ^
JSONParser.swift:217:21: error: 'index(_:offsetBy:limitedBy:)' is deprecated: all index distances are now of type Int
        guard input.index(loc, offsetBy: 4, limitedBy: input.count) != input.count else {
                    ^
```

**Comment by zwaldowski** [comment]
This looks like a source compatibility bug, the code as written should be able to use the new `Int`-based overloads just fine. I'll look around to see if it's been reported yet.

**Comment by alanzeino** [comment]
Important to note; we use -Wall and `SWIFT_WARNINGS_AS_ERRORS = YES`. These are likely warnings being converted to errors in our codebase.

From Apple's perspective, new warnings aren't source incompatibility.

**Comment by zwaldowski** [comment]
> new warnings aren't source incompatibility

That's true, but what I'm trying to say is that shouldn't trigger a warning: `3` should be passed as `Int` just like it is passed as `IndexDistance` right now.

**Comment by alanzeino** [comment]
Yeah you are right. `IndexDistance` is deprecated but if it's passing it as `Int` then this shouldn't appear.

```
    @available(*, deprecated, message: "all index distances are now of type Int")
    public typealias IndexDistance = Int
```
