### ISSUE TITLE
3.0 using deprecated API

### ISSUE THREAD

**Issue by adamdahan** [bignerdranch/Freddy#277]
Please update the JSONDecodable.swift when you have a chance!

- WARN  | xcodebuild:  Freddy/Sources/JSONDecodable.swift:60:43: warning: 'characters' is deprecated: Please use String or Substring directly
    - WARN  | xcodebuild:  Freddy/Sources/JSONDecodable.swift:61:41: warning: 'characters' is deprecated: Please use String or Substring directly

Thanks :) :) :)

**Comment by zwaldowski** [comment]
Addressed via #280.
