### ISSUE TITLE
Parser differs in behavior from NSJSONSerialization when a key is repeated in an object

### ISSUE THREAD

**Issue by hitsvilleusa** [bignerdranch/Freddy#62]
Given the following JSON:

```
{"a" : 1,"a" : 2}
```

The `NSJSONSerialization` class returns the first value `1` for the key `a`.

The BNR `JSONParser` returns a value of `2`.

I am not suggesting that the BNR version is incorrect, as I believe that the BNR version is more predictable, but it is an instance where the two diverge.

Should we:

1. Document the difference
2. Ignore the difference
3. throw an error if the key is repeated
4. change the behavior to match Apple's
5. something else

**Comment by zwaldowski** [comment]
Closing in favor of #106 since there's been more active discussion over there. No hard feelings, @hitsvilleusa.
