### ISSUE TITLE
Would it make sense to isolate the code that uses `NSJSONSerialization` into its own file

### ISSUE THREAD

**Issue by hitsvilleusa** [bignerdranch/Freddy#66]
Currently the `JSONParsing.swift` file defines the `JSONParserType` protocol and adds an extension to make `JSON` conform to it.

There is also an extension to make `NSJSONSerialization` conform to it.

I would advocate pulling the `NSJSONSerialization` conformance out into a separate file so that the reliance on `Foundation` is isolated and doesn't pollute the pure swift awesomeness.

**Comment by randomstep** [comment]
@jeremy-w fixed this in #131.
