### ISSUE TITLE
Large integers cause overflows, especially on 32-bit hosts

### ISSUE THREAD

**Issue by zwaldowski** [bignerdranch/Freddy#76]
Follow-on from #57. Consensus was that `JSON.Int` should continue to use `Swift.Int` as its associated type, but that still leaves the issue of overflows at hand. The stdlib asserts inside the parser, generally bringing down the whole app as a result.

Options include:
* Switch the parser to the `&+` et. al. operators and explicitly allow overflows.
* Switch the parser to the `addWithOverflow(_:_:)` et. al. functions, catch overflows, and throw errors, thus cancelling the parse.
* Switch the parser to the `addWithOverflow(_:_:)` et. al. functions, catch overflows, and return `String`s for big integers. This might require some workflow changes in the parser.
* Switch the parser to the `addWithOverflow(_:_:)` et. al. functions, catch overflows, and return `Double`s for big integers. (undesirable, but I mention it)

## Workaround
If this is a problem for you today, you can work around it by using Apple's parser rather than Freddy's via `JSON(data:usingParser:)` and specifying the parser as `NSJSONSerialization.self`.

```swift
// assuming you have data: NSData
let json = try JSON(data: data, usingParser: NSJSONSerialization.self)
```

For a bit more discussion around this, see [this comment below.](https://github.com/bignerdranch/Freddy/issues/76#issuecomment-189315726)

## Discussion Summary
Eventual decision was to avoid overflow by treating numbers that would overflow as strings. The value can be pulled out and then parsed from the string if needed by the user of the API. Implemented in #152 and expected to land in Freddy v2.1.

**Comment by randomstep** [comment]
I like the approach of the string initializer handling numbers: `json.string(ReallyBigInt)`. Then they can try to get the number out of the string safely if that is what they need. Does this approach have negative implications for the parser?

**Comment by zwaldowski** [comment]
Yes.

**Comment by matthewpalmer** [comment]
Not sure if this is the same problem, but wanted to post in here before creating a new issue. I'm seeing a crash on an iPhone 5 (but not on the simulator though) when parsing large doubles.

Say I have some JSON

```js
{
    "double": 1456452690075.86
}
```

And call `JSON(data:)` on that, I get a crash in `decodeNumberPreDecimalDigits`. Presumably this is because it's greater than `Int.max`, correct? Is there any way around this crash?

As a side node I think this makes the `JSON.double` methods a little misleading.

Thanks very much

(My REST API returns dates as time elapsed since 1970 in milliseconds, hence the large numbers.)

**Comment by jgallagher** [comment]
It is the same problem, yeah. The parser (currently) accumulates into an `Int` until it finds evidence that the number isn't integral (the `.` in your case), so it's crashing due to the value before it gets to the point where it switches over to `Double`. On 32-bit devices, `Int` is only 32 bits, so the cap for crashy values is much lower.

I don't think this makes `JSON.double` misleading - if the parser didn't crash, `.double` would correctly grab the value out.

We're working on a solution to this (e.g., #137). Until we land that or something like it, you can work around this by switching to the `NSJSONSerialization`-based parser:

```swift
// assuming you have data: NSData
let json = try JSON(data: data, usingParser: NSJSONSerialization.self)
```

although this will be noticeably slower for large JSON documents.

**Comment by matthewpalmer** [comment]
Thanks for getting back to me so quickly! Ah okay that all makes sense. I had no idea it was that easy to use an alternate parser, so that makes me very happy because I love the API around retrieving values once parsed. Thanks for all the hard work :+1:

**Comment by jgallagher** [comment]
Sure thing! This is exactly why we left in the fallback to `NSJSONSerialization`. Didn't want to assume the Swift parser was 100% bug-free. :)

**Comment by matthewpalmer** [comment]
@jgallagher tried to adopt the NSJSONSerialization parser, and still seeing unexpected behaviour. Sorry, I think I must be doing something wrong, but just can't work out what it is.

```json
{
   "date": {
       "$date": 1456519428000
   }
}
```

With the following code

```swift
let jsonFromNSJSON = try! NSJSONSerialization.JSONObjectWithData(data, options: [])
print(jsonFromNSJSON)
        
let jsonFromFreddyWithNSJSON = try! JSON(data: data, usingParser: NSJSONSerialization.self)
print(jsonFromFreddyWithNSJSON)
```

The first one prints the correct value for the date, but the second one prints `525514656`.

Any idea for what's going wrong?

Thanks very much,
Matt

**Comment by jeremy-w** [comment]
I was hoping to repro this, but Swift is unavailable for 32-bit OS X, my device is arm64, and I don't know of a way to run the Simulator as a 32-bit executable. :\

I can see what you're talking about looking at the code, though. This raises the point that overflow-handling affects not only the custom parser but also working with `NSJSONSerialization`. The `Int` -> `String` coercion on overflow we talked about would be doable there, I think.

**Comment by zwaldowski** [comment]
@jeremy-w: The simulator for a 32-bit device, such as the iPhone 5, should run as a 32-bit process.

**Comment by matthewpalmer** [comment]
Not sure if I misunderstand, but I'm running this on 10.11 in an iPhone 5 simulator.

From my perspective (missing a lot of the surrounding info that you guys have, of course), I'd prefer if it stayed as a number, or if Int64 was used throughout (I figure that was the topic of #57). That `case` line feels like an implicit check against that anyway. Or we could check if the value exceeds the max and bump it up to a Double if it does.

**Comment by jeremy-w** [comment]
I coded it up, and the path doesn't get hit in 64-bit processes. When I feed my 64-bit OS X build Swift.Int.max + 1 as the date value, CFNumber reads it in as a `double`. (Then I hit a crash trying to put the too-big-for-Int into an Int.) I guess this comes down to CFNumber not supporting unsigned backing storage, so once the value exceeds the 64-bit signed range, it bumps up?

**Comment by jeremy-w** [comment]
Trying to run the MobileFreddy tests on iPhone 5, and I get a "run destination not compatible" error. #ThanksXcode

**Comment by matthewpalmer** [comment]
Seeing the same here. I figure NSJSONSerialization is putting the value through as an Int64, but Freddy's trying to use an Int32, so the value overflows. I think this would affect any value in (Int32.max...Int64.max) on a 32-bit device

**Comment by jeremy-w** [comment]
Oops, I fed it UINT64_MAX+1 earlier. But INT64_MAX+1 on a 64-bit machine still results in a double.

As a workaround, pulling out the value using the `json.double(path)` accessor should give you the value without blowing up, and it should be exact for the range you need to work with Unix timestamps. Seeing as `NSTimeInterval` is a `double` anyway, that should play well with munging into an `NSDate`, if that's where you're headed.

**Comment by siuying** [comment]
I noticed the issue when I test my app on 32bit device, all JSON parsing will just fail. I expected the big integer issue and workaround it by accessing the string version of the field, but Freddy will always fail even I didn't touch the big integer field.

```swift
let str = "{\"id\": 598458199574970368, \"id_str\": \"598458199574970368\"}"
let data = str.dataUsingEncoding(NSUTF8StringEncoding)!
let json = try? JSON(data: data)
XCTAssertEqual(try json!.string("id_str"), "598458199574970368")
```

I'd expect the parser fail at ``json.int("id")``, but instead it will just failed at parsing stage. **There is currently no way for Freddy to parse a JSON contains a big integer, even we didn't use it.**

IMHO the "parse as string" workaround is not necessary, if people need big integer in JSON, they probably using string value already. A Integer value is just not a String value.

**Comment by jeremy-w** [comment]
@siuying There is actually: Use the configurable parser support to use Apple's parser if that's what you need do, as described [here](https://github.com/bignerdranch/Freddy/issues/76#issuecomment-189468487). I'll edit the issue description at the top to include the workaround.

**Comment by siuying** [comment]
@jeremy-w thanks for the pointer! I like Freddy, and I'll have to support parsing file with big integer, this definitely give me best of both worlds.

**Comment by tylerarnold** [comment]
so is there actually a way to currently parse big integers on 32-bit ARM even using NSONSerialization?
I get the following when I run the following unit test : 
<img width="831" alt="screen shot 2016-04-26 at 1 10 37 pm" src="https://cloud.githubusercontent.com/assets/130237/14829374/9f44f6f4-0bb0-11e6-9f42-9dbf945bf8ce.png">

**Comment by jeremy-w** [comment]
You're right – that isn't working as a workaround because of the JSON building. It avoids the crash, but mangles the value:

```
we got us an nsnumber: 1466719200000 - type is 4, float type? false
```

That's `.SInt64`. The cases in `NSJSONSerialization.makeJSON(object:)` assume that if it ain't a char and ain't floating, then it fits in an `Int`, which is wrong on 32-bit platforms.

**Comment by tylerarnold** [comment]
unfortunately I do not have control over that JSON format, I guess I could do some temporary hackery to force all the date formats to float before handing them off to the parser for now or try to fix this locally.

**Comment by jeremy-w** [comment]
I've brought the 32-bit issue up on #152, so we should be able to fix this along with the other overflow issues.

**Comment by purrrminator** [comment]
Due to this issue, In our project, we have to switch from Freddy to SwiftyJSON. Weird that you don't have `case  Int64` in your JSON.

**Comment by ericmaxwell2003** [comment]
Freddy turns `Int` and `Double` types into NSNumbers as part of the serialization process.  Couldn't the Swift guys just take a add NSNumber as a type in the JSON enum and then return the raw value as shown below?  Or am I missing something..

 ```
private func toJSONSerializationValue() -> Any {
        switch self {
       . . . 
        case .NSNumber(let nsNum) 
            return nsNum
        case .double(let num):
            return NSNumber(value: num)
        case .int(let int):
            return NSNumber(value: int)
       . . .
        }
```

**Comment by jeremy-w** [comment]
NSNumber is not a bignum implementation, so the problem reappears on 64-bit platforms once you overflow the range of a signed 64-bit integer, and NSNumber still does not resolve the issue. It would add another layer of wrapping and clumsiness, but not solve the underlying issue.

**Comment by ericmaxwell2003** [comment]
Gotcha.  So NSNumber would solve the problem of using Freddy to serialize/deserialize Int64s on a  on a 32 bit platform but not serializing/deserializing integers larger than 64 bits on a 64 bit platform.  

Could you just explicitly add support for Int64?  Or Int64 and Int32?

**Comment by jgallagher** [comment]
We haven't seen a way to add support for the sized integers without making the common case (`Int`) more painful/onerous. The stringification solution is far from perfect, but lets Freddy not explode on big ints _and_ not lose information.
